### ISSUE TITLE
Keep getting "Failed to install Prisma Client" when I run "pnpm run dev"

### ISSUE THREAD

**Issue by dogezhou** [prisma/nuxt-prisma#15]
follow the guide https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/prisma-nuxt-module
but this error keeps 
```
PS C:\Users\auser\Documents\codebase\test-nuxt-app> pnpm run dev

> nuxt-app@ dev C:\Users\auser\Documents\codebase\test-nuxt-app
> nuxt dev

Nuxt 3.12.2 with Nitro 2.9.6                                                                                  17:41:21
                                                                                                              17:41:23
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

✔ Prisma CLI is already installed.                                                                           17:41:35
✔ Prisma schema file exists.                                                                                 17:41:35
✔ Database migrations folder exists.                                                                         17:41:36
                                                                                                              17:41:36
Not migrating the database.
Generating Prisma client...                                                                                   17:41:36


 ERROR  ✘ Failed to install Prisma Client.                                                                    17:41:54


                                                                                                              17:42:02
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (v5.16.0) to .\node_modules\.pnpm\@prisma+client@5.16.0_prisma@5.16.0\node_modules\@prisma\client in 61ms

? Do you want to view and edit your data by installing Prisma Studio in Nuxt DevTools? » (Y/n)
```

**Comment by ankur-arch** [comment]
Hey @dogezhou, thanks for reporting the issue.

Does your app work as expected despite the error?

Can you manually install the library and check if the error persists: `pnpm i @prisma/client`

**Comment by Dobefu** [comment]
Hello hello,

This is an issue that I am encountering as well. Unfortunately, installing the client manually doesn't change the error. 
My thought was that it may not be able to find the file, because it expects the `node_modules` directory to have the structure that `npm` provides, not `pnpm`.

My solution to this is to create a `.npmrc` file with the contents `shamefully-hoist=true` in it, after which I delete `node_modules` and run `pnpm install` again.

While this appears to get us a step further, it now takes quite a bit longer to run into the same error.

I've also tried to add `generateClient: false` in the Nuxt config, since I do have a `lib/prisma.ts` that was generated in the project. This does make it so that the project will start, so it appears to be a valid workaround.

I'd like to debug it some more, but that will have to wait until after my work day. But I hope that these insights will help for anyone who comes across the same issue in the meantime.

**Comment by Dobefu** [comment]
I've eaten supper, and looked further into the issue.

It appears that the issue happens in the `setup-helpers.ts`, on line 178. It assumes the use of NPM as a package manager. And indeed, running `npm install` in the repository using `pnpm` takes a while before eventually failing. Which isn't ideal.

This pretty much explains why setting the `generateclient: false` config works, since it skips the step entirely. It also means that it is likely to fail on all other package managers, though I would have to actually test that.

I'd like to experiment with this a bit, since I'm wondering if we can infer the package manager from the running NodeJS process. If so, we can make it semi-dynamic. If not, maybe a config option would do the trick. I will probably submit a PR for this soon™.

In any case, the `.npmrc` file with the `shamefully-hoist=true` will be needed when using `pnpm`. To avoid confusion for people setting it up, maybe a note in the quick setup guide will help?

**Comment by Dobefu** [comment]
Well, what do you know. I've read through the source code a bit more, and quickly found out that multiple package managers have already been taken into account. This can easily be reused, and a PR will be coming in shortly.

I have also tested some more, and found out that I was wrong about the `.npmrc`. It appeared to run into a different error after changing it, since it took so much longer. This is not the case, however. It just has more to resolve, and is a lot slower as a result.

**Comment by ankur-arch** [comment]
Hey @Dobefu thanks for opening the PR. However, it seems that using `pnpm` to install the client, causes Prisma Studio to stop working. I'll need to investigate a bit further on this.

**Comment by Dobefu** [comment]
Hi @ankur-arch!

Thank you for checking out the PR! Prisma Studio does seem to work just fine for me, though. Could you please tell me what issue you are getting? I imagine I'm missing something in my own testing, and I'd like to help you help us in fixing the issue.

**Comment by ankur-arch** [comment]
@Dobefu I'll test it out tonight by doing a dev release. That's when the issue starts happening, especially with pnpm where Prisma Studio doesn't work on the browser. 

And has this error in the console:

```bash

Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@prisma+client@5.15.0_prisma@5.15.0/node_modules/@prisma/client/index-browser.js?v=d257c71d' does not provide an export named 'PrismaClient' (at plugin.mjs?v=d257c71d:2:10)

```

**Comment by Dobefu** [comment]
Hi @ankur-arch! Have you had to opportunity to look into this yet? I've gotten the same error you mentioned, but this happens without my changes for me as well

**Comment by ankur-arch** [comment]
Hey @Dobefu , does Prisma Studio not work for you at all when using pnpm or are you receiving the error and the studio still works?

**Comment by Dobefu** [comment]
Hi @ankur-arch,
Let me get back to you on that, it has been a hot second. I do remember that it starts working after a certain command, but I do not recall which one it is. Let me get back to you after my workday.

**Comment by ankur-arch** [comment]
Thanks @Dobefu 😄 .

**Comment by Dobefu** [comment]
Alright, update time. First of all, I'm tired. So I'll continue tomorrow after work.

Second of all, I've set up a debugger to step through the code. I'm doing this because I cannot get rid of the error like I did before. I thought it was a manual `npx prisma generate` that did the trick, but that does not seem like it's the case.

From what I can see at a glance, is that some instance of the Prisma client is being created. Albeit in a different file than I expected.

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/9e38d8f6-55d5-4a9d-a838-dc8aa48e1ef0">

**Comment by Dobefu** [comment]
Alrighty, I've gotten it semi-working on PNPM now. Hoisting the Prisma dependencies helps.
I did notice two things, though:
- I'm almost out of coffee, but that's not relevant
- I now get a hydration error, and it's not the lack of coffee

I've pushed the change for the hoist pattern, but the PR is not yet ready to be merged, on account of the hydration error. I'll look into why a Nuxt Island (basically a server component) can even get a hydration error.

**Comment by Dobefu** [comment]
Hi @ankur-arch,

I've now solved the hydration error as well. It appears to be an unrelated issue where the template cannot have multiple children.

Something to note when testing: since the `package-lock.json` files are in the repo, the code will find these before finding the `pnpm-lock.yaml` files. This means that `npm` will be used instead of `pnpm` when testing, unless these files are deleted first.

**Comment by ankur-arch** [comment]
Thanks, @Dobefu for the clarity on this 😄.

I noticed you removed the [hoist pattern](https://github.com/prisma/nuxt-prisma/commit/03d319ca5b815b0db641df4b8c1cb0d67db27a3a), I wonder if it would be helpful to add the hoist-pattern directly to the package `.npmrc`, I'll see if your solution works and merge it in.
 
(Also, I think coffee is mostly relevant)

**Comment by ankur-arch** [comment]
Thanks @Dobefu hoisting helped ensure the Prisma Studio opens up, I have a PR to guide users to do that in the docs. The latest release contains the changes from your PR 😄  (`v0.0.35 `).

**Comment by Dobefu** [comment]
Thank you for thinking along, and thanks for merging!

**Comment by stephanepericat** [comment]
I am running into the same issue with version 0.0.35 and `yarn build` :(
