### ISSUE TITLE
stop prompting me for studio

### ISSUE THREAD

**Issue by acidjazz** [prisma/nuxt-prisma#28]
how can i stop this prompt when running `pnpm run dev` ? and just have it install if its a local/dev environment but not prod?

**Comment by Dobefu** [comment]
Hi @acidjazz!

You might be looking for the `autoSetupPrisma` option in `nuxt.config.ts`. This will automagically accept all prompts. It does a bit more than you're asking, but maybe it will help you.
Example:
```js
export default defineNuxtConfig({
  modules: [
    "@prisma/nuxt",
  ],
  prisma: {
    autoSetupPrisma: true,
  }
})

```

**Comment by ankur-arch** [comment]
@acidjazz let us know if that helped achieve what you were looking for.

**Comment by ankur-arch** [comment]
Closing as this should be [acceptable workaround](https://github.com/prisma/nuxt-prisma/issues/28#issuecomment-2268729249).

**Comment by acidjazz** [comment]
@ankur-arch you shouldnt close this because of workaround - you also shouldnt prompt in a nuxt module like this, when you write to nuxt config/etc the `run dev` restarts prompting over and over

**Comment by ankur-arch** [comment]
Thanks for getting back @acidjazz! I closed this issue because:

- The studio installation is skipped if it's not [dev](https://github.com/prisma/nuxt-prisma/blob/main/src/module.ts#L182)

And the `autoSetupPrisma ` config option exists so that you'd be able to skip the prompts.

In case, you want the default behaviour to be promptless installation of Prisma Studio (to improve the experience), we'd need a separate issue for that.

**Comment by acidjazz** [comment]
@ankur-arch I get that, and that is fine.  but if someone doesn't specify `autoSetupPrisma` and then writes to their nuxt config their envrionment will hang until they realize they will be ask this question every time.  I'm just trying to clarify that this is s pretty tough experience

**Comment by ankur-arch** [comment]
@acidjazz I'll see to improving the experience with the auto setup in the next release.
