### ISSUE TITLE
`usePrismaClient` Typing Generated As "Any"

### ISSUE THREAD

**Issue by henryowens** [prisma/nuxt-prisma#40]
After creating my schema, running `pnpm dev` and also `npx prisma gernerate` the typing returned from the `usePrismaClient` is any:

<img width="833" alt="Screenshot 2024-09-18 at 17 02 51" src="https://github.com/user-attachments/assets/b6bafcd1-ee46-4e08-9fdd-77f8ff8a9b5a">

I was expecting this to have the relevent typing from my schema.

When I use the typing from `/lib/prisma.ts` it is typed correctly though.
<img width="994" alt="Screenshot 2024-09-18 at 17 05 09" src="https://github.com/user-attachments/assets/0b01e0cf-b4b4-40a1-8ee3-55fc91250193">

**Comment by ankur-arch** [comment]
Hey @henryowens 👋 

I really appreciate you opening this issue and apologize for the delay in addressing it. We're in the process of cleaning up the entire workflow for the Nuxt module to ensure issues are managed more efficiently.

Regarding this issue, could you confirm if it still occurs in version `1.1.0`? 

For now, please note that you'll need to run `npx prisma generate` with pnpm. I'm actively working on improving support for all package managers. 

<img width="1328" alt="image" src="https://github.com/user-attachments/assets/c4f31eb9-69ea-4ff6-96b9-792262bda9f0">

**Comment by ulysse-lacour** [comment]
A pity @henryowens never bothered to answer because I'm also facing same issue. Did you managed to fix it in the end ?

I'm using pnpm and my app is dockerized but whether i ran it in docker or locally issue remains the same and I'm using 

@ankur-arch unfortunately using either npx or pnpm for running migration doesn't solve anything for me

```js
const prisma = usePrismaClient();
```

Returns pisma typed any BUT when using 

```js
import prisma from '~/lib/prisma'
```

Returns well typed prisma.

Beside that everything works well with both client import type, fetching works, seeding too etc

I can work with that but I'm unsure of the use of the module then. Attached belllow also my package.json

<img width="519" alt="Image" src="https://github.com/user-attachments/assets/381a9327-9849-4975-9828-143ecb49ed96" />

<img width="812" alt="Image" src="https://github.com/user-attachments/assets/e9e36261-ff4c-4f1a-b29d-3c9d65ce059b" />

<img width="602" alt="Image" src="https://github.com/user-attachments/assets/e66972e8-eb84-4ca4-bfcb-9f429fba2066" />
